server:
  port: 7002

eureka:
  instance:
    hostname: eureka7002.com #eureka服务端的实例名称
  client:
    #单机
    #表示是否将自己注册进Eurekaserver默认为true
    #register-with-eureka: true
    #false表示不向注册中心注册自己。
    register-with-eureka: false


    #单机：
    #fetch-registry: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetch-registry: false
    service-url:
      #设置与Eureka server交互的地址查询服务和注册服务都需要依赖这个地址。
      #集群方式
      defaultZone: http://eureka7001.com:7001/eureka/
      #单机：
      #defaultZone: http://localhost:7002/eureka